spring:
  application:
    name: eufloria
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/eufloria
    username: postgres
    password: ismoil_0709
  liquibase:
    change-log: db/changelog/master-changelog.xml
    enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
