spring:
  application:
    name: eufloria

  liquibase:
    change-log: db/changelog/master-changelog.xml
    enabled: true
jwt:
  token:
    secret:
      expiry: 31560000000
      key: VGhpcyBpcyBrZXkgZm9yIEpXVApNeSBuYW1lIGlzIElzbW9pbApNeSBiaXJ0aCBkYXkgMDcuMDkuMjAwNw==